name: afyef
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_storage: ^11.5.0
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.12.2
  flutter_launcher_icons: ^0.13.1
  image_picker: ^0.8.4+9
  connectivity_plus: ^5.0.2
  intl: ^0.18.1



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true


  assets:
    - images/



